FROM rust:alpine

RUN apk add --no-cache bash clang lld zig
RUN cargo install --locked cargo-zigbuild

WORKDIR /build

# Only copy in things needed to build
COPY ./Cargo.toml .
COPY ./Cargo.lock .
COPY ./src ./src
COPY ./scripts ./scripts

ENTRYPOINT ["/build/scripts/docker/build_release_container.sh"]
