# This job builds test kernels and uploads them to the `test-assets` dummy
# release as assets.
#
# It works by looking at the KERNELS file in the root of this repository
# and checks it against all the already-uploaded kernels.

name: Kernels

on:
  push:
    branches: [ "master" ]
    paths:
      - 'KERNELS'

concurrency:
  # Ensure only a single instance of this job is run at any time
  group: ${{ github.ref }}

jobs:
  build-upload:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Calculate needed kernels
      id: calculate
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        existing=$(gh release view test_assets --json assets --jq '.[][].name')

        # Begin multiline output parameter
        echo "NEEDED_KERNELS<<MULTILINE_EOF" >> "$GITHUB_OUTPUT"

        echo "$existing" | python3 -c '
        import sys

        # Calculate kernels that have already been uploaded
        existing = {line.strip() for line in sys.stdin}
        with open("./KERNELS", "r") as f:
            lines = {line.strip() for line in f if line.strip()}

        # Print to stdout kernel we need to build and upload
        for line in lines:
            parts = line.split()
            name = f"bzImage-{parts[0]}-{parts[1]}"
            if name not in existing:
                print(line)
        ' >> "$GITHUB_OUTPUT"

        # End multiline output parameter
        echo "MULTILINE_EOF" >> "$GITHUB_OUTPUT"

    - name: Build needed kernels
      run: |
        needed=${{ steps.calculate.outputs.NEEDED_KERNELS }}
        for args in ${needed}; do
            # NB: we want to word split here
            ./scripts/build_kernel.sh $args
        done

    - name: Upload freshly built kernels
      run: |
        for kernel in bzImage-*; do
          gh release upload test_assets "$kernel"
        done
